### PR TITLE
Create sample check for GLM.jl performance evaluation and visualization

### PR DESCRIPTION
**Pull request by Ashvith10**
I've created a sample `GLM.jl` check using `PerfChecker.jl`.

Files included:

- Allocation checks (`allocs.jl`)
- Benchmark checks (`bench.jl`)
- Check files (inside `mallocs` and `benchmarks`, stored as CSV)
- Visualization files (inside `mallocs` and benchmarks, generated as PDF, PNG, SVG and Tikz)
- Package management file (`Project.toml`)

In my opinion, `bench.jl` needs to be reviewed - I've reduced the `seconds` parameter to 100 (line 24), which is probably a bad idea.

### CODE REVIEW

**Comment by Azzaare** [comment]
bench

As you can see, on my machine, with the 100 seconds limit, about 30 runs are done. So, I don't think it is an issue.

From those plots, we can see that GLM has been quite stable performance wise beside an alloc improvement at 1.3.10. Which is nice.

**Comment by Azzaare** [comment]
Based on the results for GLM.jl, maybe it is useful to prune the targeted versions. I would propose to keep the following:
- versions 1.3.9~11 to keep track of the change in allocations
- versions 1.X.0 for X in 4..8
- last release: 1.8.2

Please don't hesitate to select versions differently if you feel it makes more sense.

**Comment by Ashvith10** [comment]
> bench
> 
> As you can see, on my machine, with the 100 seconds limit, about 30 runs are done. So, I don't think it is an issue.
> 
> From those plots, we can see that GLM has been quite stable performance wise beside an alloc improvement at 1.3.10. Which is nice.

This confusion has stemmed from the reference [bench.jl](https://github.com/Humans-of-Julia/PatternFolds.jl/blob/main/perf/bench.jl) at `PatternFolds.jl`, where the `seconds` was set to 3600, and I was under the assumption that this should be in the order of 3 or more. Anyway, now I know that we're good to go, albeit after completing the pruning of unneeded versions.

**Comment by Ashvith10** [comment]
> Based on the results for GLM.jl, maybe it is useful to prune the targeted versions. I would propose to keep the following:
> 
>     * versions 1.3.9~11 to keep track of the change in allocations
> 
>     * versions 1.X.0 for X in 4..8
> 
>     * last release: 1.8.2
> 
> 
> Please don't hesitate to select versions differently if you feel it makes more sense.

I do not have any complains with your suggestions. I'll push another commit to remove the unneeded files.

**Comment by Azzaare** [comment]
Thank you for the changes. Could you also check the two remarks I made in my review?

**Pull request merged**
